# mkDevContainer - Generate podman run scripts for development containers
#
# This is the core function of llm-devcontainer. It takes a project configuration
# and produces shell scripts that launch properly-configured containers.
#
# Security model:
# - Read-only root filesystem (--read-only)
# - No new privileges (--security-opt no-new-privileges)
# - Drop all capabilities (--cap-drop ALL)
# - User namespace isolation (--userns=keep-id)
# - Minimal writable paths via tmpfs
# - Persistent auth volume for credentials (~/.claude)
#
# References:
# - https://docs.podman.io/en/latest/markdown/podman-run.1.html
# - https://man.archlinux.org/man/slirp4netns.1

{ pkgs
, lib ? pkgs.lib
}:

let
  # Helper to generate conditional mount flags
  # Returns empty string if path doesn't exist
  conditionalMount = hostPath: containerPath: opts:
    ''
      if [[ -e "${hostPath}" ]]; then
        MOUNTS+=("-v" "${hostPath}:${containerPath}:${opts}")
      fi
    '';

in
{
  # Main function to create a development container configuration
  #
  # Arguments:
  #   name          - Project name (used for auth volume naming)
  #   projectPath   - Absolute path to project directory on host
  #   image         - Container image name (default: llm-devcontainer:latest)
  #   extraMounts   - Additional volume mounts [{host, container, opts}]
  #   extraEnv      - Additional environment variables {NAME = "value"}
  #   networkMode   - Network mode: "pasta", "slirp4netns", "host" (default: "pasta")
  #   extraArgs     - Additional podman arguments (list of strings)
  #
  # Returns:
  #   Attribute set with shell scripts for different use cases
  mkDevContainer =
    { name
    , projectPath
    , image ? "llm-devcontainer:latest"
    , extraMounts ? []
    , extraEnv ? {}
    , networkMode ? "pasta"
    , extraArgs ? []
    }:

    let
      # Sanitize project name for use in volume names
      sanitizedName = lib.replaceStrings [" " "/" "\\"] ["-" "-" "-"] name;

      # Auth volume name - persists credentials across container runs
      # Mounted directly at ~/.claude for simplicity
      authVolume = "claude-auth-${sanitizedName}";

      # Build extra mount flags
      extraMountFlags = lib.concatMapStringsSep " \\\n    " (m:
        ''-v "${m.host}:${m.container}:${m.opts}"''
      ) extraMounts;

      # Core podman run arguments shared by all variants
      coreArgs = ''
        # Image and basic options
        IMAGE="${image}"

        # Security options
        SECURITY=(
          "--read-only"
          "--cap-drop=ALL"
          "--security-opt=no-new-privileges"
        )

        # User namespace: map container UID to host UID
        # This ensures file permissions work correctly with bind mounts
        USERNS="--userns=keep-id"

        # Network mode
        # pasta is preferred (faster, more features)
        # slirp4netns is fallback for older Podman versions
        NETWORK="--network=${networkMode}"

        # Writable tmpfs mounts for runtime data
        # These paths need to be writable but don't persist
        # Ownership handled by --userns=keep-id
        TMPFS=(
          "--tmpfs=/tmp:rw,exec,nosuid,nodev,size=2g"
          "--tmpfs=/var:rw,noexec,nosuid,nodev,size=512m"
          "--tmpfs=/run:rw,noexec,nosuid,nodev,size=64m"
          "--tmpfs=/home/developer/.cache:rw,exec,nosuid,nodev,size=2g"
          "--tmpfs=/home/developer/.local:rw,exec,nosuid,nodev,size=1g"
          "--tmpfs=/home/developer/.npm:rw,exec,nosuid,nodev,size=512m"
        )

        # Core volume mounts
        MOUNTS=(
          # Nix store - read-only, shared with host
          "-v" "/nix/store:/nix/store:ro"

          # Project workspace - read-write
          "-v" "${projectPath}:/workspace:rw"

          # Auth volume mounted directly at ~/.claude for credential persistence
          "-v" "${authVolume}:/home/developer/.claude:rw"
        )
      '';

      # Conditional host config mounts
      hostConfigMounts = ''
        # SSH config for git operations (read-only)
        ${conditionalMount "$HOME/.ssh" "/home/developer/.ssh" "ro"}

        # Git config
        ${conditionalMount "$HOME/.gitconfig" "/home/developer/.gitconfig" "ro"}
        ${conditionalMount "$HOME/.config/git" "/home/developer/.config/git" "ro"}
      '';

      # Build the interactive run script
      # mode parameter controls behavior: "shell" (default), "claude"
      runScript = pkgs.writeShellScript "llm-devcontainer-run" ''
        #!/usr/bin/env bash
        # llm-devcontainer container launcher
        # Generated by mkDevContainer.nix
        #
        # Project: ${name}
        # Workspace: ${projectPath}
        #
        # Usage:
        #   llm-devcontainer-run [shell|claude] [args...]
        #   llm-devcontainer-run shell        # Interactive shell (default)
        #   llm-devcontainer-run claude ...   # Run claude with args

        set -euo pipefail

        MODE="''${1:-shell}"
        shift 2>/dev/null || true

        ${coreArgs}

        ${hostConfigMounts}

        # Extra mounts from configuration
        ${if extraMounts != [] then ''
        # Additional configured mounts
        MOUNTS+=(
          ${extraMountFlags}
        )
        '' else ""}

        # Extra environment variables
        ENV_VARS=(
          ${lib.concatStringsSep "\n          " (
            lib.mapAttrsToList (k: v: ''"-e" "${k}=${v}"'') extraEnv
          )}
        )

        # Extra podman arguments
        EXTRA_ARGS=(
          ${lib.concatMapStringsSep "\n          " (a: ''"${a}"'') extraArgs}
        )

        # Determine container name and command based on mode
        case "$MODE" in
          claude)
            CONTAINER_NAME="llm-devcontainer-claude-${sanitizedName}"
            CMD=(claude --dangerously-skip-permissions "$@")
            ;;
          shell|*)
            CONTAINER_NAME="llm-devcontainer-${sanitizedName}"
            CMD=("$@")
            ;;
        esac

        # Ensure auth volume exists
        podman volume create "${authVolume}" 2>/dev/null || true

        # Construct final podman command
        exec podman run \
          --rm \
          -it \
          --name "$CONTAINER_NAME" \
          --hostname "llm-devcontainer" \
          $USERNS \
          $NETWORK \
          "''${SECURITY[@]}" \
          "''${TMPFS[@]}" \
          "''${MOUNTS[@]}" \
          "''${ENV_VARS[@]}" \
          "''${EXTRA_ARGS[@]}" \
          "$IMAGE" \
          "''${CMD[@]}"
      '';

      # Script to start container in detached mode
      detachedScript = pkgs.writeShellScript "llm-devcontainer-detached" ''
        #!/usr/bin/env bash
        # Start llm-devcontainer in detached mode
        set -euo pipefail

        ${coreArgs}

        ${hostConfigMounts}

        ${if extraMounts != [] then ''
        MOUNTS+=(
          ${extraMountFlags}
        )
        '' else ""}

        ENV_VARS=(
          ${lib.concatStringsSep "\n          " (
            lib.mapAttrsToList (k: v: ''"-e" "${k}=${v}"'') extraEnv
          )}
        )

        EXTRA_ARGS=(
          ${lib.concatMapStringsSep "\n          " (a: ''"${a}"'') extraArgs}
        )

        CONTAINER_NAME="llm-devcontainer-${sanitizedName}"

        # Ensure auth volume exists
        podman volume create "${authVolume}" 2>/dev/null || true

        # Check if already running
        if podman ps --format "{{.Names}}" | grep -q "^$CONTAINER_NAME$"; then
          echo "[llm-devcontainer] Container already running, attaching..."
          exec podman attach "$CONTAINER_NAME"
        fi

        # Start detached
        podman run \
          --rm \
          -d \
          --name "$CONTAINER_NAME" \
          --hostname "llm-devcontainer" \
          $USERNS \
          $NETWORK \
          "''${SECURITY[@]}" \
          "''${TMPFS[@]}" \
          "''${MOUNTS[@]}" \
          "''${ENV_VARS[@]}" \
          "''${EXTRA_ARGS[@]}" \
          "$IMAGE" \
          sleep infinity

        echo "[llm-devcontainer] Container started: $CONTAINER_NAME"
        echo "[llm-devcontainer] Attach with: podman attach $CONTAINER_NAME"
        echo "[llm-devcontainer] Exec shell:  podman exec -it $CONTAINER_NAME /bin/zsh"
      '';

    in {
      # Main run script - supports shell and claude modes
      run = runScript;

      # Convenience aliases
      shell = pkgs.writeShellScript "llm-devcontainer-shell" ''
        exec ${runScript} shell "$@"
      '';

      claude = pkgs.writeShellScript "llm-devcontainer-claude" ''
        exec ${runScript} claude "$@"
      '';

      # Detached container with attach capability
      detached = detachedScript;

      # Metadata for introspection
      meta = {
        inherit name projectPath image authVolume;
        inherit extraMounts extraEnv networkMode;
      };
    };
}
